vim.g.transparent_groups = vim.list_extend(vim.g.transparent_groups or {}, {
  'NoiceCmdlinePopup',
  'NoiceCmdlinePopupBorder',
  'NoiceCmdlineIcon ',
  'NoiceCmdlinePopupBorderCmdline',
  'NoiceCmdlineIconCmdline',
  'NoiceCmdlinePopupBorderSearch',
  'NoiceCmdlineIconSearch',
  'NoiceCmdlinePopupBorderLua',
  'NoiceCmdlineIconLua',
  'NoiceCmdlinePopupBorderFilter',
  'NoiceCmdlineIconFilter',
  'NoiceCmdlinePopupBorderHelp',
  'NoiceCmdlineIconHelp',
  'DiagnosticSignHint',
  'DiagnosticSignInfo',
  'DiagnosticSignWarn',
  'DiagnosticSignError',
  'GitSignsAdd',
  'GitSignsChange',
  'GitSignsDelete',
  'GitSignsStagedAdd',
  'GitSignsStagedChange',
  'GitSignsStagedDelete',
  'NotifyINFOBody',
  'NotifyINFOBorder',
  'NotifyWARNBody',
  'NotifyWARNBorder',
  'NotifyERRORBody',
  'NotifyERRORBorder',
  -- 'Folded',
  'FoldColumn',
})
